### ISSUE TITLE
sqlite_busy_timeout not preserved in cloned dbh

### ISSUE THREAD

**Issue by zdm** [DBD-SQLite/DBD-SQLite#20]
Cloned dbh always has default sqlite_busy_timeout value (30000).

**Comment by charsbar** [comment]
I'm not sure exactly what you are doing, but from what you've said above, it looks like you are doing something you are not expected to do such as (re)using a forked dbh, which may corrupt your database (because SQLite typically uses POSIX advisory locks) and thus should be avoided.

I suppose you should find a way not to clone a dbh (by making a new connection to the database after fork() etc), but if you think you do need to clone, could you show me some code that explains what you are trying to achieve?

DBD::SQLite itself only undef $drh in the CLONE sub.

**Comment by zdm** [comment]
1. I created handle $dbh1;
2. Call $dbh1->sqlite_busy_timeout(10000);
3. Call my $dbh2 = $dbh1->clone;
4. Check sqlite_busy_timeout for cloned $dbh2 and see, that it value is not 10000;

I need to set sqlite_busy_timeout manually again for each cloned dbh, if clone method just clean drh?

**Comment by charsbar** [comment]
Ah, yes, you need to set sqlite_busy_timeout manually again, because DBI's "clone" method only creates a new dbh using the same connect closure. It's implemented in pure perl, so see https://metacpan.org/source/TIMB/DBI-1.636/DBI.pm#L1536 and https://metacpan.org/source/TIMB/DBI-1.636/DBI.pm#L677 for details. It's probably not what you might have assumed.

This is probably not an issue of DBD::SQLite, though it might be useful if we can set sqlite_busy_timeout via connect attribute, like ```DBI->connect('dbi:SQLite::memory:', undef, undef, {sqlite_busy_timeout => 10000})```.

**Comment by zdm** [comment]
Yes, attribute instead of the method would be useful.
Ok, thank you very much, it's clear for me now how it's works.
