### ISSUE TITLE
FTS5 Support?

### ISSUE THREAD

**Issue by lbe** [DBD-SQLite/DBD-SQLite#48]
All,

Are there any plans to implement FTS5 support?  I saw the open ticket with the point on future compatibility and @damil comment from +/- 2 years ago.

While I have used Sqlite for years, actually make that decades :), this is my first need for FTS.  The data set that I will be working with has 32,000,000+ records.  I am concerned about the instance lists being too long FTS4.  I am starting testing on this as soon as I click Submit on this issue.  If this is a problem, then FTS5 should take care of it.

Thanks in advance,

lbe

**Comment by damil** [comment]
Hi,

I don't have any personal experience with FTS5, but somme colleagues use 
it, and apparently there is no need for any specific support from the 
DBD driver, since most FTS5 operations are based on SQL statements 
without any C-level bindings. The -FTS5 compile option is activated by 
default, so you can use it right away. The only features which are not 
available in the current version of DBD::SQLite are specific auxiliary 
functions or specific tokenizers (see 
https://sqlite.org/fts5.html#extending_fts5); but unless you have very 
specific needs, it is unlikely that you would miss such features.

Regards, Laurent Dami


Le 04.03.2019 à 15:54, lbe a écrit :

**Comment by lbe** [comment]
@damil, Thank you for your prompt response and clarification.  I don't anticipate needing custom tokenizing so I will experiment with FTS5.

I will close this issue at this time and re-open if needed!

Thanks again!

**Comment by nuclight** [comment]
Now it seems that FTS5 custom tokenizer is needed, any progress on this?..
