### ISSUE TITLE
perl DBI SQLite commit or detach fails when AutoCommit is set to false when another DB is attached

### ISSUE THREAD

**Issue by ludz-lim** [DBD-SQLite/DBD-SQLite#49]
The following statement fails when $dest is created with AutoCommit => 0:
$dest->commit();
$dest->do("DETACH DATABASE chunk_db");

Below is a code segment that reproduces the error

`use DBI;`

`unlink glob("*.db3");`
`my $source = DBI->connect("dbi:SQLite:dbname=first.db3",q(),q(),{AutoCommit => 0, RaiseError =>1});`

`$source->do("CREATE TABLE test(x integer)");`
`$source->do("INSERT INTO test(x) values (1)");`
`$source->commit();`
`$source->disconnect();`

`my $dest = DBI->connect("dbi:SQLite:dbname=second.db3",q(),q(),{AutoCommit => 0, RaiseError =>1});`

`$dest->do("CREATE TABLE test(x integer)");`
`$dest->do("ATTACH DATABASE 'first.db3' AS chunk_db");`
`$dest->do("INSERT INTO test(x) SELECT x FROM chunk_db.test");`

`# will fail here when AutoCommit => 0`
`$dest->commit;`
`# If the previous commit statement is omitted, this will also fail with AutoCommit => 0`
`$dest->do("DETACH DATABASE chunk_db");`
`$dest->disconnect();`

My platform is perl v 5.24 (Strawberry perl) on Windows 10

**Comment by charsbar** [comment]
Sorry for the late reply. Though the error message ```database chunk_db is locked``` is rather confusing, I think this is because ATTACH/DETACH is not allowed within transaction. It should be clearer if you run sqlite3 and execute ATTACH after BEGIN statement; you'll see an error message like: ```Error: cannot ATTACH database within transaction```. This error should be gone if you begin transaction after you attach a database, and end it before you detach the database.
