### ISSUE TITLE
sqlite_db_filename returns "" instead of undef

### ISSUE THREAD

**Issue by dboehmer** [DBD-SQLite/DBD-SQLite#50]
The method `sqlite_db_filename` is documented to return `undef` for in-memory databases.
https://metacpan.org/pod/DBD::SQLite#$dbh-%3Esqlite_db_filename()

But instead it returns an empty string:

```
$ perl -w -MDBI -E 'say defined ? qq("$_") : "undef" for DBI->connect("dbi:SQLite::memory:")->sqlite_db_filename; say $DBD::SQLite::VERSION'
""
1.62
```

I'm not confident enough in C to fix this in code. If you'd rather adjust the documentation to the existing behavior I can provide a PR.

**Comment by charsbar** [comment]
Thanks for spotting this. Until recently, the comment in sqlite3.c has said like this:
```
If there is no attached database N on the database
** connection D, or if database N is a temporary or in-memory database, then
** a NULL pointer is returned.
```

However, it has actually been returning an emtpy string or NULL depending on the situation, at least since 2013. And now, the latest version of sqlite3.c has changed its comment as follows.
```
 If there is no attached database N on the database
** connection D, or if database N is a temporary or in-memory database, then
** this function will return either a NULL pointer or an empty string.
```

I committed a change in the pod. I'm not going to release this today, but it's about time to release the next stable version, so I think this commit will be in soon.
