### ISSUE TITLE
Enable custom compliler defines at configure?

### ISSUE THREAD

**Issue by mlawren** [DBD-SQLite/DBD-SQLite#60]
I was originally going to ask if -DSQLITE_DQS=0 could be added to the build to stop double quoted identifiers[1] from being accepted. Then I considered that possibly not everyone else would agree and that there are also other defines that I would like to set easily at build time without manually modifying Makefile.PL.

So my feature request is actually to enable the passing of -D flags through to the compiler via an environment variable at the time Makefile.PL is run.

[1] https://www.sqlite.org/quirks.html#dblquote

**Comment by charsbar** [comment]
Well, if you just need that feature, you can use ```db_config``` method and ```SQLITE_DBCONFIG_DQS_DML``` and ```SQLITE_DBCONFIG_DQS_DDL``` constants to modify the default settings at runtime, without affecting other applications and, more likely, module tests that use DBD::SQLite. Isn't it enough for you?

I'm reluctant to allow users to customize DBD::SQLite at compile time because that has made it harder for other modules' maintainers to get exactly what breaks their modules (from CPAN Testers' reports, etc). We've disabled a few options to use system SQLite for years for that reason, and allowing new environmental variables to modify compile options doesn't fit the tradition.

**Comment by mlawren** [comment]
Thanks for the fast response!

On Tue Feb 11, 2020 at 08:07:18AM -0800, Kenichi Ishigaki wrote:
> Well, if you just need that feature, you can use ```db_config```
> method and ```SQLITE_DBCONFIG_DQS_DML``` and
> ```SQLITE_DBCONFIG_DQS_DDL``` constants to modify the default
> settings at runtime, without affecting other applications and, more
> likely, module tests that use DBD::SQLite. Isn't it enough for you?

I was unaware of the db_config method... but I also can't find any
reference to that in the POD or find either of those constants in
DBD::SQLite::Constants. Where is it documented?

> I'm reluctant to allow users to customize DBD::SQLite at compile time
> because that has made it harder for other modules' maintainers to get
> exactly what breaks their modules (from CPAN Testers' reports, etc).

It seems you see it as a trade-off between tester convenience and user
convenience. Does it have to be though? Is AUTOMATED_TESTING (or
whatever the variable is called) set on testers' boxes during the
configure phase?.  What about a patch that only enables changes via the
environment when that is not set?

Is it even possible for environment values in one distribution to
affect how other dists are built on testers boxes? My understanding is
that dists get whatever minimum dependencies happen to be installed on
smokers' boxes - not a fresh install of everything each run. I
certainly wouldn't be relying on the possibility of such behaviour.

My use case is to try and make SQLite a bit stricter during development
and to occasionally test features which are not on by default or only
available in not-yet-released SQLite amalgamations to drop into the
DBD-SQLite source directly. I guess I can work from the Git sources
directly, but if modifying Makefile.PL had been easier then I wouldn't
have opened this request.

-- 
Mark Lawrence

**Comment by charsbar** [comment]
>> On Tue Feb 11, 2020 at 08:07:18AM -0800, Kenichi Ishigaki wrote: Well, if you just need that feature, you can use ```db_config``` method and ```SQLITE_DBCONFIG_DQS_DML``` and ```SQLITE_DBCONFIG_DQS_DDL``` constants to modify the default settings at runtime, without affecting other applications and, more likely, module tests that use DBD::SQLite. Isn't it enough for you?
> I was unaware of the db_config method... but I also can't find any reference to that in the POD or find either of those constants in DBD::SQLite::Constants. Where is it documented?

- https://metacpan.org/pod/DBD::SQLite#$dbh->sqlite_db_config(-$id,-$new_integer_value-)
- https://metacpan.org/pod/DBD::SQLite::Constants#database_connection_configuration_options
- https://metacpan.org/source/ISHIGAKI/DBD-SQLite-1.64/t/65_db_config.t#L268-311
- http://sqlite.org/c3ref/c_dbconfig_defensive.html#sqlitedbconfigdqsddl

I agree that there's a lot of room to improve here.

>> I'm reluctant to allow users to customize DBD::SQLite at compile time because that has made it harder for other modules' maintainers to get exactly what breaks their modules (from CPAN Testers' reports, etc).
> It seems you see it as a trade-off between tester convenience and user convenience. Does it have to be though? Is AUTOMATED_TESTING (or whatever the variable is called) set on testers' boxes during the configure phase?. What about a patch that only enables changes via the environment when that is not set?
> Is it even possible for environment values in one distribution to affect how other dists are built on testers boxes? My understanding is that dists get whatever minimum dependencies happen to be installed on smokers' boxes - not a fresh install of everything each run. I certainly wouldn't be relying on the possibility of such behaviour.

This is not a problem for smoking testers who usually don't touch anything but AUTOMATED_TESTING. The problem is that someone who actually develops an application and has customized DBD::SQLite installed may find something weird while installing (or using) another module that uses DBD::SQLite (internally or for testing) and report it as a bug to the maintainer of the module, who of course has only tested it with the ordinary version of DBD::SQLite and wonders why. The maintainer or the reporter will eventually find it's not an issue of the module but the customization, but that's a waste of time, especially of the maintainer of a popular module who gets a lot of reports. So we decided not to allow casual customization.

> My use case is to try and make SQLite a bit stricter during development and to occasionally test features which are not on by default or only available in not-yet-released SQLite amalgamations to drop into the DBD-SQLite source directly. I guess I can work from the Git sources directly, but if modifying Makefile.PL had been easier then I wouldn't have opened this request.

You might want to try ``` perl Makefile.PL DEFINE="-DSQLITE_DQS=0 -DTHREADSAFE=0 ..."```, though you need to define everything by youself. See the pod of ExtUtils::MakeMaker for details. ( https://metacpan.org/pod/ExtUtils::MakeMaker#Using-Attributes-and-Parameters ).

**Comment by mlawren** [comment]
On Wed Feb 12, 2020 at 09:09:34PM -0800, Kenichi Ishigaki wrote:
> - https://metacpan.org/pod/DBD::SQLite#$dbh->sqlite_db_config(-$id,-$new_integer_value-)
> - https://metacpan.org/pod/DBD::SQLite::Constants#database_connection_configuration_options
> - https://metacpan.org/source/ISHIGAKI/DBD-SQLite-1.64/t/65_db_config.t#L268-311
> - http://sqlite.org/c3ref/c_dbconfig_defensive.html#sqlitedbconfigdqsddl
> 
> I agree that there's a lot of room to improve here.

*facepalm* my ```man DBD::SQLite``` check was picking up the
old system-installed POD, not my development version. Grrr... sorry.

> This is not a problem for smoking testers who usually don't touch
> anything but AUTOMATED_TESTING. The problem is that someone who
> actually develops an application and has customized DBD::SQLite
> installed may find something weird while installing (or using)
> another module that uses DBD::SQLite (internally or for testing) and
> report it as a bug to the maintainer of the module, who of course has
> only tested it with the ordinary version of DBD::SQLite and wonders
> why. The maintainer or the reporter will eventually find it's not an
> issue of the module but the customization, but that's a waste of
> time, especially of the maintainer of a popular module who gets a lot
> of reports. So we decided not to allow casual customization.

All clear. Thanks for the background.

> > My use case is to try and make SQLite a bit stricter during
> > development and to occasionally test features which are not on by
> > default or only available in not-yet-released SQLite amalgamations
> > to drop into the DBD-SQLite source directly. I guess I can work
> > from the Git sources directly, but if modifying Makefile.PL had
> > been easier then I wouldn't have opened this request.
> 
> You might want to try ``` perl Makefile.PL DEFINE="-DSQLITE_DQS=0
> -DTHREADSAFE=0 ..."```, though you need to define everything by
> youself. See the pod of ExtUtils::MakeMaker for details. (
> https://metacpan.org/pod/ExtUtils::MakeMaker#Using-Attributes-and-Parameters
> ).

That... is almost as good! Thanks for the hint.

-- 
Mark Lawrence
